# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-06 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20220305_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='property',
        ),
        migrations.AddField(
            model_name='activity',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.Property', verbose_name='Property'),
        ),
    ]
