# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-06 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20220305_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('done', 'Done')], default='active', max_length=35, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=35, verbose_name='Status'),
        ),
    ]
