# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-07 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20220306_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='active', max_length=35, verbose_name='Status'),
        ),
    ]
